
2022-04-02 21:53:17,767 INFO: errors [in C:\Users\pawel.debinski\source\repos\Fyyur_udacity\app.py:510]
